name: Cypress Tests

on:
  push:
    branches:
      - Project123  # Change to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Set execution permission for Cypress binary
      if: ${{ runner.os == 'Windows' }}
      run: icacls node_modules\\.bin\\cypress /grant Users:(RX)

    - name: Run Cypress tests
      run: npx cypress run
