name: Cypress Tests

on:
  push:
    branches:
      - Project123  # Change to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

    - name: Install dependencies
      run: npm install

    - name: List contents of node_modules/.bin
      run: ls -l node_modules/.bin

    - name: Set execution permission for Cypress binary
      run: chmod +x node_modules/.bin/cypress

    - name: Run Cypress tests
      run: |
        npx cypress run --browser chrome --headless || (echo "Cypress tests failed" && exit 1)
