name: Cypress Tests

on:
  push:
    branches:
      - Project123  # Change to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Cypress binary
      uses: actions/cache@v2
      with:
        path: /home/runner/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

    - name: Install system dependencies
      run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

    - name: Install dependencies
      run: npm install

    - name: Set execution permission for Cypress binary
      run: |
        chmod +x /home/runner/.cache/Cypress/12.16.0/Cypress/Cypress

    - name: Run Cypress tests
      run: |
        /home/runner/.cache/Cypress/12.16.0/Cypress/Cypress run --browser chrome --headless --cache-path /home/runner/.cache/Cypress || (echo "Cypress tests failed" && exit 1)
